#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  untitled.py
#  Generated by Geany 1.22
#  
#  Author:	Edward Osorio S.
#  Date:	2014-12-13
#  Version:	1.0
#  Mail:	osorio.edd@gmail.com
#  
#  Copyright 2014
#  

import os
import csv

def main():
	#Directorio
	path = '/home/dobleub/Github/posgradostnm/basicapp/docs/oficios/posgrados/'	# linux
	#path = 'C:\Ruta\a\directorio\' #windows
	 
	lstFiles = []
	lstDir = os.walk(path)
	
	fh = open(path + 'listaArchivos.csv','w')
	 
	for root, dirs, files in lstDir:
		for fichero in files:
			(nombreFichero, extension) = os.path.splitext(fichero)
			if(extension == ".pdf" or extension == ".PDF"):
				lstFiles.append(nombreFichero+extension)
				arrayNames = nombreFichero.split(' ')
				objCsv = csv.writer(fh, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
				objCsv.writerow(arrayNames)
	
	fh.close()
	#print(lstFiles)
	print ('\nLISTADO FINALIZADO')
	print "longitud de la lista = ", len(lstFiles)
	
	return 0

if __name__ == '__main__':
	main()

